"""initial schema

Revision ID: 2f9c1045e7d7
Revises:
Create Date: 2026-05-04 12:59:18.595432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f9c1045e7d7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "token_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("api_type", sa.String(length=50), nullable=True),
        sa.Column("api_base", sa.String(length=500), nullable=True),
        sa.Column("api_key", sa.String(length=500), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("test_count", sa.Integer(), nullable=True),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("multiplier", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["token_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "test_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("ttft_ms", sa.Float(), nullable=True),
        sa.Column("tps_overall", sa.Float(), nullable=True),
        sa.Column("tps_generate", sa.Float(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("total_time_ms", sa.Float(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_read", sa.Integer(), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=True),
        sa.Column("token_density", sa.Float(), nullable=True),
        sa.Column("ttfb_ms", sa.Float(), nullable=True),
        sa.Column("ttfr_ms", sa.Float(), nullable=True),
        sa.Column("think_time_ms", sa.Float(), nullable=True),
        sa.Column("content_tokens", sa.Integer(), nullable=True),
        sa.Column("thinking_tokens", sa.Integer(), nullable=True),
        sa.Column("tps_content", sa.Float(), nullable=True),
        sa.Column("content_char_count", sa.Integer(), nullable=True),
        sa.Column("thinking_char_count", sa.Integer(), nullable=True),
        sa.Column("ping_ms", sa.Float(), nullable=True),
        sa.Column("ping_samples", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("debug_chunks", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["token_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("test_results_mig_test")
    op.drop_table("test_results_0_1_0")
    op.drop_table("test_results_ci")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_results_ci",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "ttfb_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ttfr_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "think_time_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("content_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("thinking_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "tps_content",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "content_char_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "thinking_char_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ping_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ping_samples", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "brand_new_col",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("test_results_ci_pkey")),
    )
    op.create_table(
        "test_results_0_1_0",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "ttfb_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ttfr_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "think_time_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("content_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("thinking_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "tps_content",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "content_char_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "thinking_char_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ping_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ping_samples", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("name2", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "v020_test",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("test_results_0_1_0_pkey")),
    )
    op.create_table(
        "test_results_mig_test",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "ttfb_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ttfr_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "think_time_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("content_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("thinking_tokens", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "tps_content",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "content_char_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "thinking_char_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ping_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ping_samples", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("test_results_mig_test_pkey")),
    )
    op.drop_table("test_results")
    op.drop_table("users")
    op.drop_table("token_plans")
    op.drop_table("settings")
    # ### end Alembic commands ###
